spring:
  application:
    name: ticket-master

  datasource:
    url: jdbc:postgresql://localhost:5435/ticketbooking
    username: ticket_user
    password: ticket_pass
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
